### ISSUE TITLE
Windows Containers not reachable through k8s service. PR that solves that seems to be available.

### ISSUE THREAD

**Issue by jomeier** [openshift/ovn-kubernetes#265]
Hi,

I'm running in the problem this PR seems to fix:

https://github.com/ovn-org/ovn-kubernetes/pull/1385

On OKD 4.5 I'm able to bootstrap a Windows node in my cluster and also the communication between a linux pod and a windows pod is working. 

But if I try to connect to the windows pod through a k8s service on my linux node, it isn't working. 

I used http://skydive.network/ to analyze the network setup and it seems that the problem described in the PR occurs in my cluster.

Also @aravindhp told me in this slack chat:
https://kubernetes.slack.com/archives/C6BRQSH2S/p1597171732277400?thread_ts=1597154582.264500&cid=C6BRQSH2S
that this PR is necessary for getting Windows Containes working in a hybrid network.

Thank you and greetings,

Josef

**Comment by aravindhp** [comment]
@jomeier this fix is included in 4.6. We are not planning to support Windows Containers in OKD 4.5 and only in OKD 4.6+.

**Comment by jomeier** [comment]
@aravindhp 
My problem is that windows-machine-config-bootstrapper is also not working with OKD 4.6

The Ansible installer does not find a 4.6 tag. Only 4.5 tags are available in that repository.

**Comment by aravindhp** [comment]
We are not supporting the Ansible playbook with OKD 4.6. We will release a community version of [WMCO](https://github.com/openshift/windows-machine-config-operator) shortly.

**Comment by jomeier** [comment]
@aravindhp 
Without that there is no way to get Windows containers running with vSphere because I assume the WMCO will only support major cloud providers (Azure,AWS,...).

Will the WMCO also support vSphere in that Release?

**Comment by aravindhp** [comment]
>  I assume the WMCO will only support major cloud providers (Azure,AWS,...)

We are striving to get vSphere (not baremetal) supported in the 4.6 time frame but it is not a given. Unfortunately we cannot support both the operator and the Ansible playbook at the same time.

**Comment by aravindhp** [comment]
But to go back to your original question about ovn-org/ovn-kubernetes#1385, I will defer to the @openshift/openshift-team-sdn if that is going to be backported to 4.5.

**Comment by jomeier** [comment]
Thx. I‘m closing this issue.
