### ISSUE TITLE
Add option to build ovn-kubernetes without authentication (by community users)

### ISSUE THREAD

**Issue by jomeier** [openshift/ovn-kubernetes#274]
Hi,

almost all images required for OKD 4 can be built by community users. One exception of that is the image from this repository.

```
...
Step 10/32 : RUN yum install -y      selinux-policy &&     yum clean all
 ---> Running in 01784f0dd84f
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
http://base-4-0.ocp.svc/rhel-fast-datapath/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: base-4-0.ocp.svc; Unknown error"
Trying other mirror.


 One of the configured repositories failed (rhel-fast-datapath),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
```

I talked with @elmiko about how to proceed with that and he asked me for opening a ticket.

Here it is :-) Could you provide an option so non Red Hatters can build this image on their own, please?

Thank you and best regards,

Josef

**Comment by elmiko** [comment]
one thing i noted to Josef is that internally (at Red Hat) there has been some suggestion that the image pull specs in these dockerfiles should replace `/ocp/` with `/origin/` to get the public, non-subscription based, images. i tried this out with the dockerfile in this repo, but i was not able to produce an image yet.

**Comment by danwinship** [comment]
There are currently no publicly-downloadable versions of the RHEL OVS/OVN packages that the Dockerfiles here use.

I believe you should be able to build from `dist/images/Dockerfile.fedora` and get something mostly correct though; that's the Dockerfile used to build the images used for CI in the upstream repo, so it should always be pulling in the correct package versions, etc.

**Comment by danwinship** [comment]
> There are currently no publicly-downloadable versions of the RHEL OVS/OVN packages that the Dockerfiles here use.

I should not have said "currently". Assume that this is not going to change.
