### ISSUE TITLE
openshift/origin-ovn-kubernetes image does not contain kubectl binary

### ISSUE THREAD

**Issue by danwinship** [openshift/ovn-kubernetes#5]
As currently built, the openshift/origin-ovn-kubernetes image does not contain `kubectl`, meaning that even with #4 the node still can't start

**Comment by pecameron** [comment]
Can we just eliminate the need for kubectl in the image? It is quite large.

**Comment by danwinship** [comment]
Not trivially; `ovnkube.sh` uses it to find the address of the nbdb and sbdb to pass to `ovnkube --init-node`.

In theory we could change ovnkube to let us say `--nb-service=openshift-ovn-kubernetes/ovn-northd --sb-service=openshift-ovn-kubernetes/ovn-southd` instead, and then ovnkube would do the lookup rather than having the wrapper script do it. That might be nice.

**Comment by danwinship** [comment]
> In theory we could change ovnkube to let us say `--nb-service=openshift-ovn-kubernetes/ovn-northd`

actually we don't even need to do that; we can just create kube Services for northd and southd and then add, eg

    env:
    - name: OVN_NORTH
      value: tcp://ovn-northd.openshift-ovn-kubernetes.svc:6641
    - name: OVN_SOUTH
      value: tcp://ovn-southd.openshift-ovn-kubernetes.svc:6642

and it can resolve the service IP via DNS. But that still requires rewriting stuff because currently it always uses kubectl to check the ovnkube-master service to figure out when it can start the ovn node

**Comment by squeed** [comment]
Maybe, though we often come up before kube-dns, so it's probably better to add native service support directly.

**Comment by dcbw** [comment]
@squeed @danwinship isn't this (and some other PRs) diverging from the upstream script? Shouldn't we be copying upstream into our downstream repo first, and anything we need to fix, doing that upstream first and then pulling downstream?

**Comment by danwinship** [comment]
> Maybe, though we often come up before kube-dns, so it's probably better to add native service support directly.

ah, indeed. meh

> isn't this (and some other PRs) diverging from the upstream script? Shouldn't we be copying upstream into our downstream repo first, and anything we need to fix, doing that upstream first and then pulling downstream?

In my most recent comments I meant to imply making those changes upstream, not here.

For the moment, I am trying to get this repo to a point where we can get ovn-kube to actually come up and work. Once that happens, I'll start upstreaming fixes and rebasing. It doesn't make sense to spend time filing PRs upstream now since we can't even test them yet, and don't actually know if they're going to work.

**Comment by pecameron** [comment]
Maybe it would be good to merge upstream onto this repo and start with that?

**Comment by dcbw** [comment]
@danwinship Right, but there's a pretty big delta between upstream and what's in openshift's downstream repo. IMHO it would be better to copy over what's upstream, and start from there, otherwise you have to do some work twice.
